### ISSUE TITLE
Whenever the script is sourced, a new bash completion script is created

### ISSUE THREAD

**Issue by ierturk** [toradex/tcb-env-setup#1]
Whenever the script is sourced, a new bash completion script is created

**Comment by sergioprado** [comment]
Thanks for reporting @ierturk .

That is very strange because we remove the script after sourcing it (see line 194).

Can you provide more information about your environment? Operating system, shell implementation, shell version, etc.

**Comment by ierturk** [comment]
Hi @sergioprado,

I experienced the issue on Manjaro/Arch system with ZSH shell. I checked the script on openSUSE-Tumblewwed, and it works as expected.

Thanks and regards.
